spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car?useSSL=false
    username: root
    password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    enabled: false

mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER



  jpa:
    hibernate:
      ddl-auto: create

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

